version: '3.8'

services:
  # Main Go application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: helloworld-app
    ports:
      - "8080:8080"
    volumes:
      # Mount source code for hot reload (excluding unwanted folders)
      - .:/app
      # Mount Go cache for faster builds and tool installations
      - go_cache:/go
    environment:
      - GO_ENV=development
      - PORT=8080
      - CGO_ENABLED=0
      - GOTOOLCHAIN=local
      - GOFLAGS=-buildvcs=false
    restart: unless-stopped

  # PostgreSQL database (optional for now)
  postgres:
    image: postgres:15-alpine
    container_name: helloworld-postgres
    environment:
      POSTGRES_DB: helloworld
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  go_cache: 