version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: helloworld-app-prod
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=production
      - PORT=8080
      - CGO_ENABLED=0
      # Database connection will be set via environment variables
      # - DATABASE_URL=postgres://user:pass@host:port/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25' 